name: Multi Platform Release

on:
  push:
    tags:
    - '*'    

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
       go-version: '^1.21.1'

    - name: Install Dependencies
      run: cd ${{ github.workspace }} && powershell ./install.ps1

    - name: Setup Environment Variables
      run: |
         dir ${{ github.workspace }}\templibs
         echo "${{ github.workspace }}\templibs\liboqs" >> $GITHUB_PATH
         echo "${{ github.workspace }}\templibs\hybrid-pqc" >> $GITHUB_PATH
         echo "${{ github.workspace }}\templibs\pkg-config\bin" >> $GITHUB_PATH
         echo "${{ github.workspace }}\templibs\mingw\mingw64\bin" >> $GITHUB_PATH
         
    - name: Build
      env:
        PKG_CONFIG_PATH: ${{ github.workspace }}\templibs\pkg-config
      run: |
         dir ${{ github.workspace }}\templibs\pkg-config
         echo %PATH%
         echo %PKG_CONFIG_PATH%
         mkdir ${{ github.workspace }}\build && go build -o ${{ github.workspace }}\build ./...

    - name: Create Release
      env:
        PKG_CONFIG_PATH: ${{ github.workspace }}\templibs\pkg-config
      
      run: |
         echo %PATH%
         echo %PKG_CONFIG_PATH%
         mkdir ${{ github.workspace }}\build\release
         cp ${{ github.workspace }}\build\dp.exe mkdir ${{ github.workspace }}\build\release\dp.exe
         cp ${{ github.workspace }}\build\dputil.exe mkdir ${{ github.workspace }}\build\release\dputil.exe
         cp ${{ github.workspace }}\templibs\liboqs\oqs.dll mkdir ${{ github.workspace }}\build\release\oqs.dll
         cp ${{ github.workspace }}\templibs\hybrid-pqc\hybridpqc.dll mkdir ${{ github.workspace }}\build\release\hybridpqc.dll
         powershell Compress-Archive ${{ github.workspace }}\build\release ${{ github.workspace }}\build\release.zip

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: hybridpqc
        path: |
              ${{ github.workspace }}/build/*.*
              
    - name: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "build/*.*"
